apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorflow-notebook.fullname" . }}-tb
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6006
      targetPort: tensorboard
      protocol: TCP
      name: tensorboard
  selector:
    app: {{ include "tensorflow-notebook.fullname" . }}-tb
    release: {{ .Release.Name }}
