apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-world.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"    
  labels:
    app: "{{ template "hello-world.fullname" . }}"
    chart: "{{ template "hello-world.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hello-world.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
