{{- if (semverCompare ">=1.15-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orders.acme.cert-manager.io
  annotations:
    cert-manager.io/inject-ca-from-secret: 'okteto/cert-manager-webhook-ca'
  labels:
    app: 'cert-manager'
    app.kubernetes.io/name: 'cert-manager'
    app.kubernetes.io/instance: 'cert-manager'
    app.kubernetes.io/managed-by: 'Helm'
    helm.sh/chart: 'cert-manager-v1.1.0'
spec:
  group: acme.cert-manager.io
  names:
    kind: Order
    listKind: OrderList
    plural: orders
    singular: order
  scope: Namespaced
  conversion:
    # a Webhook strategy instruct API server to call an external webhook for any conversion between custom resources.
    strategy: Webhook
    # webhookClientConfig is required when strategy is `Webhook` and it configures the webhook endpoint to be called by API server.
    webhook:
      conversionReviewVersions: ["v1", "v1beta1"]
      clientConfig:
        service:
          namespace: 'okteto'
          name: 'cert-manager-webhook'
          path: /convert
  versions:
    - name: v1alpha2
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .spec.issuerRef.name
          name: Issuer
          priority: 1
          type: string
        - jsonPath: .status.reason
          name: Reason
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - csr
                - issuerRef
              properties:
                commonName:
                  type: string
                csr:
                  type: string
                  format: byte
                dnsNames:
                  type: array
                  items:
                    type: string
                duration:
                  type: string
                ipAddresses:
                  type: array
                  items:
                    type: string
                issuerRef:
                  type: object
                  required:
                    - name
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                authorizations:
                  type: array
                  items:
                    type: object
                    required:
                      - url
                    properties:
                      challenges:
                        type: array
                        items:
                          type: object
                          required:
                            - token
                            - type
                            - url
                          properties:
                            token:
                              type: string
                            type:
                              type: string
                            url:
                              type: string
                      identifier:
                        type: string
                      initialState:
                        type: string
                        enum:
                          - valid
                          - ready
                          - pending
                          - processing
                          - invalid
                          - expired
                          - errored
                      url:
                        type: string
                      wildcard:
                        type: boolean
                certificate:
                  type: string
                  format: byte
                failureTime:
                  type: string
                  format: date-time
                finalizeURL:
                  type: string
                reason:
                  type: string
                state:
                  type: string
                  enum:
                    - valid
                    - ready
                    - pending
                    - processing
                    - invalid
                    - expired
                    - errored
                url:
                  type: string
      served: true
      storage: false
    - name: v1alpha3
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .spec.issuerRef.name
          name: Issuer
          priority: 1
          type: string
        - jsonPath: .status.reason
          name: Reason
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - csr
                - issuerRef
              properties:
                commonName:
                  type: string
                csr:
                  type: string
                  format: byte
                dnsNames:
                  type: array
                  items:
                    type: string
                duration:
                  type: string
                ipAddresses:
                  type: array
                  items:
                    type: string
                issuerRef:
                  type: object
                  required:
                    - name
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                authorizations:
                  type: array
                  items:
                    type: object
                    required:
                      - url
                    properties:
                      challenges:
                        type: array
                        items:
                          type: object
                          required:
                            - token
                            - type
                            - url
                          properties:
                            token:
                              type: string
                            type:
                              type: string
                            url:
                              type: string
                      identifier:
                        type: string
                      initialState:
                        type: string
                        enum:
                          - valid
                          - ready
                          - pending
                          - processing
                          - invalid
                          - expired
                          - errored
                      url:
                        type: string
                      wildcard:
                        type: boolean
                certificate:
                  type: string
                  format: byte
                failureTime:
                  type: string
                  format: date-time
                finalizeURL:
                  type: string
                reason:
                  type: string
                state:
                  type: string
                  enum:
                    - valid
                    - ready
                    - pending
                    - processing
                    - invalid
                    - expired
                    - errored
                url:
                  type: string
      served: true
      storage: false
    - name: v1beta1
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .spec.issuerRef.name
          name: Issuer
          priority: 1
          type: string
        - jsonPath: .status.reason
          name: Reason
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - issuerRef
                - request
              properties:
                commonName:
                  type: string
                dnsNames:
                  type: array
                  items:
                    type: string
                duration:
                  type: string
                ipAddresses:
                  type: array
                  items:
                    type: string
                issuerRef:
                  type: object
                  required:
                    - name
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                request:
                  type: string
                  format: byte
            status:
              type: object
              properties:
                authorizations:
                  type: array
                  items:
                    type: object
                    required:
                      - url
                    properties:
                      challenges:
                        type: array
                        items:
                          type: object
                          required:
                            - token
                            - type
                            - url
                          properties:
                            token:
                              type: string
                            type:
                              type: string
                            url:
                              type: string
                      identifier:
                        type: string
                      initialState:
                        type: string
                        enum:
                          - valid
                          - ready
                          - pending
                          - processing
                          - invalid
                          - expired
                          - errored
                      url:
                        type: string
                      wildcard:
                        type: boolean
                certificate:
                  type: string
                  format: byte
                failureTime:
                  type: string
                  format: date-time
                finalizeURL:
                  type: string
                reason:
                  type: string
                state:
                  type: string
                  enum:
                    - valid
                    - ready
                    - pending
                    - processing
                    - invalid
                    - expired
                    - errored
                url:
                  type: string
      served: true
      storage: false
    - name: v1
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .spec.issuerRef.name
          name: Issuer
          priority: 1
          type: string
        - jsonPath: .status.reason
          name: Reason
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - issuerRef
                - request
              properties:
                commonName:
                  type: string
                dnsNames:
                  type: array
                  items:
                    type: string
                duration:
                  type: string
                ipAddresses:
                  type: array
                  items:
                    type: string
                issuerRef:
                  type: object
                  required:
                    - name
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                request:
                  type: string
                  format: byte
            status:
              type: object
              properties:
                authorizations:
                  type: array
                  items:
                    type: object
                    required:
                      - url
                    properties:
                      challenges:
                        type: array
                        items:
                          type: object
                          required:
                            - token
                            - type
                            - url
                          properties:
                            token:
                              type: string
                            type:
                              type: string
                            url:
                              type: string
                      identifier:
                        type: string
                      initialState:
                        type: string
                        enum:
                          - valid
                          - ready
                          - pending
                          - processing
                          - invalid
                          - expired
                          - errored
                      url:
                        type: string
                      wildcard:
                        type: boolean
                certificate:
                  type: string
                  format: byte
                failureTime:
                  type: string
                  format: date-time
                finalizeURL:
                  type: string
                reason:
                  type: string
                state:
                  type: string
                  enum:
                    - valid
                    - ready
                    - pending
                    - processing
                    - invalid
                    - expired
                    - errored
                url:
                  type: string
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end }}