apiVersion: v2
appVersion: v0.7.6
description: A Helm chart for cert-manager crds
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
version: 0.2.0
name: cert-manager2
